import { useContext } from "react"
import { ThemeContext } from "@/store/store"


export default function Content() {
  const centralState = useContext(ThemeContext);
  console.log(centralState);


  return (
    <div className={centralState.theme === "light" ? "gb-light text-dark" : "bg-dark text-light"}>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis quam beatae officia maiores itaque. Harum consequatur vitae provident amet, nemo velit minima? Aperiam sed, facere accusantium corrupti vero soluta nihil.
      Voluptas expedita sapiente ut debitis repudiandae quidem sint beatae unde itaque quia aspernatur rerum, nostrum accusamus! Nam rem debitis omnis est, eum, provident soluta officiis, similique cumque et sint dolore?
      Minus commodi libero ipsum illo numquam pariatur ad quam, qui vero sit et, atque voluptas tempore incidunt! Provident officiis quaerat harum reprehenderit earum consequuntur dignissimos voluptatibus maiores, repudiandae corporis incidunt?
      Doloremque hic, consequatur dolore velit praesentium quaerat alias voluptatum eligendi reiciendis quos porro accusamus fugiat culpa quasi officia pariatur laudantium quas tenetur totam, aliquam reprehenderit officiis eos laborum labore. Officia?
      Aspernatur sequi porro, temporibus obcaecati libero doloribus qui quibusdam accusantium optio voluptas provident soluta earum ratione possimus maxime harum et sint, rem consectetur aliquam iste sed inventore nostrum ipsam! Aperiam.
      Cupiditate molestiae quisquam voluptas commodi, ipsum sit! Molestias suscipit labore odio aliquid vel. Sint vero voluptas, amet expedita consectetur dolor ratione a numquam aperiam ut consequuntur repellendus at odio aliquid.
      Iusto, laudantium placeat. Officia nesciunt odit accusamus est soluta veniam! Praesentium a dolore esse nemo quae, sapiente corporis, odit recusandae vitae ea minus animi. Harum, minima! Repudiandae accusamus inventore natus!
      Harum, ad! Pariatur, eos beatae quo saepe sit accusantium laboriosam soluta nobis officia veniam vero atque sunt perspiciatis veritatis totam repellendus quia iste delectus necessitatibus rerum nisi alias doloremque nostrum.
      Ratione, saepe consectetur! Cupiditate a facere id voluptate veritatis fugiat reiciendis aliquid numquam possimus aperiam sapiente quas similique beatae distinctio ipsum assumenda quia, cumque sunt maxime. Expedita cum tenetur modi.
      Dolor enim id suscipit nostrum alias, architecto libero obcaecati aperiam, earum quibusdam voluptate aut magni, quam nesciunt necessitatibus! Doloribus, odit ad quis iusto numquam nisi blanditiis nobis vel assumenda in.
      Ut vitae corporis tenetur temporibus, nulla deserunt explicabo earum laboriosam voluptatum provident corrupti vero atque iusto, incidunt dolores a laborum dolorum odit expedita maiores consequatur, voluptate sed! Sapiente, a saepe?
      Reiciendis sapiente mollitia magni ipsum vero sunt. Quisquam modi voluptatum aut, voluptatem, sed maxime quos molestias repellat nulla ea culpa consequatur exercitationem expedita ducimus hic fugit id quam. Nulla, assumenda?
      Fugit rem explicabo assumenda sunt illum cupiditate ullam doloremque maiores asperiores vitae, laborum repellat quia perferendis illo qui quae id voluptas recusandae dolore incidunt quas! Quasi officia laboriosam unde excepturi.
      Possimus, dolores labore molestiae aspernatur sit a autem fugiat corporis odio error architecto nam maxime iusto vitae quis pariatur, adipisci dicta. Harum debitis mollitia ut! Saepe, consequatur? Dolor, laboriosam! Tempore.
      Praesentium velit deleniti minus, quae odit natus accusantium eos nemo, adipisci dolor ullam iure corrupti mollitia accusamus atque. Ipsum est deserunt dolores earum hic ratione quod exercitationem ad, ipsa neque.
      Veniam perspiciatis sit, illum nisi nam facilis quam! Earum iste, officiis voluptas atque at minus explicabo sit maiores non hic totam delectus dolorum? Ratione esse iusto, qui beatae nihil quis.
      Rerum, repellendus? In optio facere beatae tenetur nobis eligendi sequi ut itaque, tempora corporis maiores aliquid, iste praesentium laboriosam earum architecto voluptate similique reiciendis enim recusandae incidunt ducimus cupiditate alias?
      Porro, vel exercitationem. Voluptatibus, doloremque nam placeat facilis libero voluptates. Id quidem reprehenderit, inventore ad nulla veritatis ducimus est ipsa libero dolorem sit eveniet nam. Impedit quisquam fuga facilis optio!
      Rem cum aliquam voluptatum veniam dolores reiciendis fuga beatae eveniet totam voluptatem, eum culpa rerum fugiat obcaecati dolor illo repudiandae consectetur quasi vero, laboriosam ab? Accusamus accusantium sint quasi voluptas!
      Enim, quaerat. Accusantium corporis voluptatum fuga ipsam aspernatur quaerat, eius atque iusto officiis deserunt placeat velit, dolores sit quisquam amet temporibus officia dolorum quis itaque! Tenetur quisquam earum quod fugiat!
      Totam reprehenderit assumenda sint vero repudiandae cumque quidem corrupti deleniti? Doloremque dolores minus quaerat mollitia adipisci nesciunt aliquid impedit. Accusamus laboriosam rerum minima corrupti earum atque, quam expedita soluta voluptatum.
      Voluptatem aperiam in sunt doloremque cumque aut culpa hic. At, nemo, natus corporis hic corrupti ducimus illo harum optio, tempora modi est! Temporibus cumque sit velit. Iste maiores dolorum ipsum!
      Quod itaque harum adipisci qui beatae est eveniet! Tempora inventore delectus accusamus praesentium iusto. Quam distinctio, dignissimos optio, rerum dolorem consequuntur autem earum praesentium, harum tempora nulla magnam repudiandae libero.
      Laborum deserunt eligendi dolorem iusto quod? Alias odit quisquam, totam nam voluptatum ut excepturi sed ratione praesentium est necessitatibus minus, libero eaque quas? Minima maiores ut eligendi! Ipsam, quis nemo?
      Nostrum, temporibus repellat dolorum fuga vero eius ab quidem deserunt exercitationem ex, architecto voluptate ipsa magni molestiae ipsam voluptates doloremque consequuntur soluta quis. Doloribus similique, nisi reiciendis quas saepe corporis?
      Ipsam quia distinctio excepturi eos amet recusandae cumque, officiis maiores doloribus quos laborum magnam a voluptate beatae deleniti ut nihil voluptates perspiciatis corporis impedit quo? Voluptas inventore voluptates culpa accusantium.
      Atque, quaerat at ratione quasi deleniti maxime officia doloribus numquam officiis repellendus eum veritatis omnis facilis in eveniet enim voluptates tenetur aperiam eligendi soluta esse porro! Est rerum libero ipsum!
      Provident sit libero sint voluptas inventore, animi nostrum voluptates. Assumenda eaque harum necessitatibus pariatur eius earum rerum optio, voluptas eveniet commodi cum! Fuga nemo iusto possimus sequi consequuntur. Voluptates, obcaecati.
      Impedit, velit molestias laboriosam aliquam consectetur hic, aspernatur repellendus quaerat porro quis esse? Natus, aut veniam incidunt sed in facilis saepe possimus magni sequi atque maxime culpa odio at? Nostrum.
      Ducimus nam molestias laboriosam, eveniet quam, quasi dicta esse tempora doloremque aliquid error doloribus? Unde eum ipsa repellendus minima vel, eligendi repudiandae facere accusamus fugit quia eos, a debitis? Voluptates.
      Dolorum, dolorem facere saepe dicta ea molestias incidunt rem? Sit exercitationem quis placeat ratione nisi aut asperiores odio magnam eos vel. Unde hic rerum obcaecati, ratione repellendus deleniti porro. Quae.
      Quibusdam ipsam minima suscipit illum ullam pariatur, modi vitae voluptatem soluta quo omnis officiis voluptatum corrupti fugiat quia deserunt perferendis sed placeat iste? Impedit, assumenda? Facere aperiam distinctio rerum quas.
      Placeat eveniet dolorem maiores nisi praesentium at voluptatum modi dolor unde. Nobis sapiente, vitae sint nihil optio, accusantium dolores porro ipsa quae repudiandae totam iure cupiditate laborum excepturi delectus? Cupiditate?
      Error accusantium iure beatae, tenetur assumenda ducimus minima porro placeat corrupti laborum. Architecto repudiandae, voluptatem rem cumque debitis fugit, facere necessitatibus et incidunt nostrum odio veniam nam suscipit nihil amet.
      Quo, ex fuga. Aut omnis repudiandae earum dolorem cum excepturi vero praesentium similique eos ullam. Unde nemo nostrum odit accusamus a. Excepturi sint quasi omnis amet, dolores blanditiis magni accusamus?
      Quisquam rem, ea esse modi vero accusantium molestias atque reprehenderit eveniet at qui, non molestiae facere quibusdam vitae architecto nisi quam eius vel error ipsa delectus. Totam, cupiditate? Tempore, maiores?
      Quis eligendi quibusdam iusto libero repudiandae sunt praesentium odio sed unde sit, aspernatur dicta est alias, tenetur architecto necessitatibus ipsam neque quod officiis omnis qui nulla repellat pariatur? Impedit, fuga!
      Accusamus totam, animi sint ut voluptatibus quidem doloribus placeat assumenda nemo vero omnis delectus rerum quas in deleniti veniam tenetur. Qui molestiae quod sapiente doloribus minima omnis non rem eum.
      Alias reiciendis, sit autem hic in adipisci eaque error repudiandae minus! Saepe magnam dignissimos minus explicabo accusamus temporibus nisi quos voluptate voluptatum quod, tenetur quidem architecto esse numquam dolore quasi.
      Reiciendis cupiditate ab, nisi voluptates placeat ipsa rerum quia. Molestiae maxime qui dignissimos harum optio aspernatur magnam sint temporibus? Aut omnis voluptatibus amet possimus perferendis, asperiores recusandae architecto nisi aliquid.
      Ab eos necessitatibus ex nam molestias possimus accusantium excepturi dolorem, voluptatum aut laudantium. Odit dolor quam hic nam velit iusto odio, atque nostrum quae quaerat. Dolore, alias harum! Aliquam, quidem.
      Illo unde quidem esse ducimus voluptate molestias corrupti ex, deserunt maxime dignissimos voluptatum accusamus nisi repellat odio nihil eos velit provident illum magni? Dolorum quod minima quisquam! Sequi, maiores molestiae!
      Repellendus unde debitis id assumenda quisquam? Ullam repudiandae tempore at velit doloribus officia ipsum quis est. Quidem enim porro molestias culpa, iusto, esse fugiat quis veniam expedita provident, magnam ut!
      Quam quasi, necessitatibus nisi quae fugiat eum. Adipisci aperiam illo placeat, labore mollitia dolorem iure facilis temporibus sint, doloribus officia, sunt alias ex quas nulla iusto recusandae? Laboriosam, dignissimos perspiciatis?
      Possimus soluta ut, voluptas optio fugiat autem est eum, sunt quo quidem inventore laborum esse. Temporibus nemo officiis accusantium! Dicta consectetur laboriosam sit dolores culpa rem est quos perspiciatis possimus?
      Voluptatibus inventore iste id distinctio. Voluptatum porro ea placeat assumenda illum vel nihil optio. Assumenda corrupti voluptate consequatur temporibus minus hic eaque, eligendi explicabo quidem nihil dignissimos alias? Sapiente, praesentium.
      Nam nulla quaerat a, quia fuga earum ex soluta veritatis possimus cum aspernatur perferendis, sapiente dolor eum numquam. Magni necessitatibus, ipsa aut eveniet autem quam? Eos, nostrum! Minus, deserunt numquam?
      Corporis accusamus alias itaque suscipit quibusdam sequi tempora similique maxime eos voluptas. Minima molestiae saepe et necessitatibus vel possimus ea magnam laudantium hic, amet eum eius, temporibus quidem libero quae.
      Non iusto magnam amet illo veritatis ipsum, nisi nulla cupiditate quidem atque fugiat est incidunt, tempora maxime omnis, voluptas assumenda aspernatur molestiae modi laboriosam necessitatibus illum asperiores perspiciatis? Libero, quod?
      Iste, eveniet assumenda amet sequi quam debitis cupiditate doloribus! Repudiandae sit nisi aperiam culpa aspernatur, ut veniam nam eveniet ipsa velit quaerat sapiente sed accusantium dolores ipsam dolorem totam deleniti.
      Doloribus aliquam nisi, saepe explicabo voluptate accusamus delectus voluptas quas nobis harum deserunt magni. Numquam eveniet saepe optio dolor velit, minus perferendis, porro ratione eligendi sapiente quo repellendus ipsam impedit.
      Quaerat suscipit vitae, ipsa assumenda ad cumque quos sapiente similique porro nisi, id accusamus reiciendis tempora veritatis vero dolor distinctio minus harum? Architecto, molestiae odit? Animi a minus numquam necessitatibus.
      Voluptas delectus facilis explicabo labore, sequi saepe id eum atque quis est ratione aspernatur corporis quia magni rem excepturi enim necessitatibus modi ipsam fugit voluptate iusto sit ad? Officiis, corporis.
      Explicabo voluptatum delectus fugiat molestias animi. Iure a blanditiis culpa, dicta accusamus quos quia vero aliquid aperiam enim? Unde quasi eligendi dolorem vero itaque cumque natus veritatis incidunt minima amet.
      Doloremque, beatae? Officia quae animi optio obcaecati similique. Accusamus omnis corrupti aut perferendis aperiam illum modi cupiditate obcaecati, assumenda suscipit voluptatum, enim consectetur porro quis dolore esse quae eius perspiciatis.
      Placeat culpa, libero qui officia dolorem esse perferendis at, dolorum, nobis sed eaque maxime iure sint sapiente in praesentium officiis! Perspiciatis nulla iusto nostrum sunt, enim culpa hic dolorem ut!
      Repellat, molestiae a iusto animi numquam impedit alias soluta quis quos, voluptatibus voluptas ab commodi error at harum ratione aliquid suscipit voluptates ad explicabo nulla aperiam quae dolorem. Iure, ipsum?
      Eligendi similique provident totam mollitia distinctio repellendus, eaque quia, exercitationem voluptates atque, rem aspernatur illum? Ipsam, consequuntur deserunt ab cum cupiditate autem dignissimos. Cupiditate doloribus natus voluptatum, porro laborum quasi!
      Asperiores rem voluptatibus ducimus esse, distinctio delectus! Praesentium animi nihil laudantium fugiat sunt ipsa architecto in rerum. Vel, laborum animi totam aliquam, harum similique ipsum, ipsa ut aperiam nesciunt expedita!
      Ea, quia modi animi in aliquid itaque cum laborum dolorum, excepturi delectus sequi eveniet deserunt architecto perferendis ducimus iusto laboriosam deleniti asperiores velit qui obcaecati soluta quas culpa. Quaerat, soluta.
      Culpa deserunt tempore adipisci repellat minus? Corporis repudiandae dignissimos dolores qui veritatis neque fugit veniam voluptates. Sunt, excepturi aliquam labore error qui deserunt in quod doloribus atque totam, odit iure.
      Accusamus, omnis aut maxime aspernatur adipisci illum nisi, inventore modi, quidem sapiente quod. Voluptate distinctio animi repellat expedita eos, qui consequatur, doloremque reprehenderit labore iste molestiae est. Perferendis, culpa quae?
      Illum assumenda porro fugiat suscipit minima quasi quas incidunt sed nisi ex earum ea veniam, modi consequatur, illo doloremque molestiae nesciunt accusantium expedita dolorem in maxime repellendus commodi? Possimus, odio.
      Expedita nobis exercitationem eaque harum ab nulla, iste officiis labore tenetur quis cupiditate laudantium ex molestias suscipit saepe minus odio numquam error blanditiis adipisci! Quidem, possimus. Amet voluptate architecto iusto.
      Assumenda veniam, incidunt impedit neque excepturi illum. Neque voluptatum, nobis laboriosam repellat cumque sit, tenetur quod at nihil odio ducimus consectetur, obcaecati facilis adipisci delectus fuga earum. Dolorem, ab? Ipsum.
      Quam quas perferendis sint ex ut esse iste aliquid, veniam aut iure molestias recusandae accusamus sapiente minima temporibus id odio repudiandae consectetur eius quae similique eaque accusantium fugit. Unde, cupiditate?
      Debitis adipisci facilis facere quae natus, libero numquam commodi rerum tempore. Expedita doloremque porro repellendus deserunt voluptates non ut, quae, debitis eum officiis reprehenderit! Placeat odio alias nulla soluta ab.
      Vel autem alias ipsum fugiat sapiente nihil libero eius distinctio! Suscipit fugiat, explicabo quis atque, consequuntur officiis qui fugit beatae nesciunt adipisci, sint quam perspiciatis officia distinctio. Sequi, quos sapiente.
      Iure architecto dolores fuga, aliquam, est facilis quos repellat fugiat enim expedita dignissimos nam minima inventore tempore impedit dicta ipsum distinctio veritatis aperiam eum pariatur? Nemo, saepe nesciunt? Quas, maxime!
      Dolor sapiente qui minus saepe quos ratione nihil eveniet veniam! Placeat, deserunt. Voluptate praesentium officia repellendus fugit sed. Quo quisquam modi veniam unde amet assumenda nam voluptatum illo dolores qui?
      Nam repellat unde modi voluptate tenetur quibusdam in aspernatur laudantium cupiditate maxime omnis obcaecati numquam et, nulla libero illo non recusandae. Architecto eum, molestiae quo dolorem quis iure praesentium neque.
      Quam eaque laborum at porro, mollitia, eum architecto esse asperiores facilis ipsa ducimus odio doloribus deleniti voluptatum illo harum explicabo dicta omnis corporis fugiat labore id quo. Eveniet, sunt velit?
      Hic, officia optio. Ratione sunt harum architecto pariatur earum ipsum minus quia accusantium molestias similique, impedit laboriosam ad odio sit eum in? Qui, molestias ratione dignissimos iure quos ipsam voluptatum!
      Omnis quasi recusandae est deserunt dolores enim eum accusantium, voluptatem animi autem! Doloremque alias esse, harum inventore consectetur sapiente. Fuga ratione quae a voluptatum sint, dicta voluptatibus eveniet. Nisi, nemo.
      Libero iusto exercitationem cupiditate nihil facilis quam voluptatem similique molestiae totam ex magni porro placeat amet quos, officiis a quibusdam aliquam minima dolorum perspiciatis voluptatibus velit ea? Impedit, corrupti laborum.
      Quas dolore, numquam blanditiis veniam error eveniet ratione. Architecto, repellendus veritatis sint dicta, nemo aperiam, molestiae ipsam nam porro rem dolorem non! Suscipit labore assumenda similique explicabo, itaque a voluptas.
      Totam commodi esse et ratione suscipit enim nemo, a provident earum sequi repudiandae quidem rerum qui! Tempore aspernatur labore corrupti quae magni dicta ab expedita, totam obcaecati perspiciatis aperiam eveniet.
      Repudiandae facilis aspernatur alias molestiae quibusdam minus accusantium maiores ullam! Exercitationem cupiditate, voluptatem aut magnam porro veniam sed obcaecati commodi velit est esse asperiores blanditiis incidunt illo tempora quae ratione.
      Expedita eius quis sit voluptatibus error laborum magni aut facere in commodi maxime corporis veniam ipsam modi, minima dolores! Necessitatibus officiis modi veritatis excepturi quia ut ducimus voluptate sit tempore!
      Nam fuga modi, quibusdam inventore cupiditate laudantium dolores deleniti vitae ratione eius debitis numquam sit aperiam cumque praesentium illum exercitationem! Magni laboriosam ullam dolorum id. Ducimus suscipit accusantium explicabo maxime?
      Veritatis illo facere dignissimos beatae eveniet. Temporibus distinctio magni tempora recusandae corporis enim magnam fugit debitis, quo eos voluptas asperiores ab quam culpa quas dolores omnis minima natus nisi placeat?
      Quaerat quae dolore, cum unde sapiente atque minus qui dolor veniam eveniet ipsum enim, consectetur voluptatum laudantium obcaecati officia debitis eum? Quaerat magnam quae aut obcaecati. At, quo. Cupiditate, ex?
      Cum saepe iusto officiis odio totam rem, sunt quisquam ullam explicabo deleniti magni at ex ratione architecto voluptatibus exercitationem corporis eligendi sint excepturi asperiores officia quia. Recusandae ipsum sapiente dicta.
      Obcaecati aut cupiditate nemo saepe iste magni quos quasi autem, at eos, illo distinctio, beatae reprehenderit maiores mollitia. Eveniet tempore molestiae architecto expedita vitae? Nulla iure commodi repellendus deleniti fugiat!
      Natus dolorem repudiandae itaque eum atque laboriosam deserunt inventore recusandae suscipit quam ut voluptatum consectetur ullam, qui earum eos repellendus autem obcaecati quod delectus nam odit enim consequatur doloribus! Sunt.
      Iure accusamus praesentium optio vero odit, ab debitis commodi nesciunt quidem deserunt veniam! Accusamus sit culpa vero aliquid unde asperiores ad non excepturi, qui eum id nulla. In, at neque!
      Doloribus, iusto perspiciatis harum cupiditate debitis consequuntur iure, non nulla neque similique molestiae adipisci odit laudantium animi. Saepe nam, deleniti itaque nihil quas laudantium, cupiditate quo commodi velit eaque dignissimos?
      Deleniti aspernatur, saepe voluptate veritatis temporibus eaque recusandae explicabo amet officia voluptates dolore quia rerum cumque, modi iste eveniet fugiat nesciunt earum enim eum consequuntur quam! Expedita veniam soluta sit.
      Corporis cumque ratione qui optio ipsam. Vel itaque eos magnam quisquam pariatur consectetur a? Quidem mollitia voluptates nostrum! Tempore totam aspernatur atque voluptatibus nesciunt necessitatibus vel quidem vero architecto. Itaque!
      Voluptatum aliquam dolorem inventore, consectetur rem non alias delectus, aliquid sed porro reprehenderit sit earum nam minima ab molestiae iure mollitia! Amet dolor ex quidem. Veritatis vitae voluptatibus enim necessitatibus.
      Corrupti, itaque quia odio impedit minima tempora iure nulla tempore repellat veritatis saepe nisi exercitationem molestias deserunt officiis distinctio accusamus excepturi animi dolore, nam eaque quasi amet! Amet, fugit nisi.
      Sunt atque numquam nam eaque illum voluptas dolore illo sequi quas architecto ullam neque assumenda pariatur ipsa molestiae, quidem voluptatibus sed ut optio quaerat labore iste consectetur ipsum. Consequuntur, dolor.
      Ad porro iure molestias quasi, voluptatem vero quibusdam modi quis, necessitatibus sunt enim ipsum, saepe rerum. Eveniet omnis totam hic cumque, sunt fugiat, magnam placeat quae qui ullam nulla earum.
      Corrupti inventore ad quo a eos dignissimos sit sapiente reiciendis quae porro doloremque non iusto pariatur possimus ut fugit libero provident quaerat facilis qui, beatae magnam quia! Sunt, nam eos.
      Impedit unde, ea exercitationem neque earum eveniet vitae eos enim est voluptate libero accusantium tenetur quibusdam, accusamus blanditiis, itaque provident. Soluta architecto mollitia aliquid in consequatur ullam consectetur nam labore.
      Corrupti, reiciendis! Aut, ullam? Incidunt quo id nemo tempore veniam animi autem voluptatum libero reprehenderit doloribus officiis, impedit omnis voluptas architecto quia ducimus soluta, laborum ex accusamus natus illum. Maxime.
      Tempora assumenda earum quia modi facilis, cupiditate tempore nobis ut porro delectus, quisquam hic nesciunt velit amet aliquid quos ea! Possimus, odio dolores ad assumenda sequi sint ut odit porro.
      Consequatur quo tempore sed sequi assumenda repellendus, recusandae atque quasi illo nisi exercitationem blanditiis aspernatur nostrum repudiandae totam rem magni, eaque tempora veniam. Consectetur magnam quia atque, deleniti dolores nam.
      Officiis soluta, laborum ad totam quia repellat ratione non beatae dolor minus molestias? Natus cupiditate quis porro deserunt sed. Obcaecati explicabo fugiat facilis a vero incidunt modi perferendis quo maxime!
      Distinctio necessitatibus nisi soluta repudiandae ipsa. Corrupti ex dolores dolore? Minima repudiandae earum fugit excepturi libero ea atque accusamus optio repellat similique placeat ad reiciendis eligendi, temporibus maxime culpa voluptates?
    </div>
  )
}
